[pgbouncer]
 listen_port = 6432
 listen_addr = *

 max_client_conn = 2000
 max_db_connections = 100

 server_reset_query_always = 1
 client_login_timeout = 10
 default_pool_size = 10

 dns_max_ttl = 600
 dns_nxdomain_ttl = 600

 server_lifetime = 1200 
 server_idle_timeout = 120

 auth_type = md5
 auth_user = sysuser_auth
 auth_query = SELECT u,p FROM login.shadow_info($1::text) a(u text,p text)
 ;auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename='user_min' and $1::text is not null
 auth_file = /etc/pgbouncer/userlist.txt
 admin_users = bouncer_adm
 
 ;logfile = pgbouncer.log
 ;pidfile = pgbouncer.pid
 ;admin_users = someuser

 [databases]
 ext_db = host=/var/run/postgresql min_pool_size=10 pool_mode=transaction 
 int_db = host=/var/run/postgresql min_pool_size=10 pool_mode=transaction 

; [users]

 [users]
 user_admin = pool_size=4
 user_sysop = pool_size=5
 user_staff = pool_size=10
 user_user = pool_size=50
 user_min = pool_size=10
 sysuser_auth = pool_size=10
