services:
  ext_app: 
    image: cosmtrek/air
    user: ${S_UID}:${S_GID}
    restart: ${RESTART_MODE}
    network_mode: ${NET_MODE}
#    ports:
#      - ${HOST_LOOPBACK_IP}:3080:80
    environment:
      - TZ=Europe/Moscow
      - GOCACHE=/go-cache
      - GOPATH=/go
      - DIST=/dist
    working_dir: /go/src
    volumes:
      - ../..:/go/src
      - ../../../../../workarea/cache/ext:/go-cache
      - ../../../../../workarea/modules/ext/pkg:/go/pkg
      - ../../../../../dist/app/ext:/dist
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - setup
