services:
  main_db: 
    image: postgres:18-alpine
    volumes:
      - ./databases/main_db/conf:/var/lib/postgresql/conf:ro
      - ./databases/main_db/storage:/var/lib/postgresql/data
      - ./workarea/sockets/main_db:/var/run/postgresql
      - ./dist/databases/main_db:/var/lib/postgresql/def:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: ${S_UID}:${S_GID}
    network_mode: ${NET_MODE}
    restart: ${RESTART_MODE}
###S_DEL_PROD    
    shm_size: 1G
###E_DEL_PROD
###E_UNCOMM_    shm_size: 93G    
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: main_db
      PGDATA: /var/lib/postgresql/data
    command: sh -c "
              printf 'postgres:x:%s:%s:PostgreSQL:%s:/bin/false\n' $(id -u) $(id -g) /var/lib/postgresql/data > /var/lib/postgresql/data/passwd;
              printf 'postgres:x:%s:\n' $(id -g) > /var/lib/postgresql/data/groups;
              LD_PRELOAD=/usr/lib/libnss_wrapper.so NSS_WRAPPER_PASSWD=/var/lib/postgresql/data/passwd NSS_WRAPPER_GROUP=/var/lib/postgresql/data/groups postgres 
               -c 'config_file=/var/lib/postgresql/conf/postgresql.conf'
               -c 'hba_file=/var/lib/postgresql/conf/pg_hba.conf' "


  main_bouncer: # this is a plain pgbounces instance
    image: edoburu/pgbouncer:v1.25.1-p0 
    network_mode: ${NET_MODE}
    restart: ${RESTART_MODE}
    volumes:
      - ./databases/main_db/bouncer-conf/etc/pgbouncer/:/etc/pgbouncer/:ro
      - ./workarea/sockets/main_db:/var/run/postgresql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: ${S_UID}:${S_GID}
    depends_on:
      - main_db
