services:
  main_db: 
    image: postgres:18-alpine
    volumes:
      - ./databases/main_db/conf:/var/lib/postgresql/data/conf
      - ./databases/main_db/storage:/var/lib/postgresql/data/storage
      - ./workarea/sockets/main_db:/var/run/postgresql
      - ./dist/databases/main_db:/lib/postgresql/data/def
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: ${S_UID}:${S_GID}
    network_mode: ${NET_MODE}
    restart: ${RESTART_MODE}
###S_DEL_PROD    
    shm_size: 1G
###E_DEL_PROD
###E_UNCOMM_    shm_size: 93G    
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: main_db
      PGDATA: /var/lib/postgresql/data/storage

  main_bouncer: # this is a plain pgbounces instance
    image: edoburu/pgbouncer:v1.25.1-p0 
    network_mode: ${NET_MODE}
    restart: ${RESTART_MODE}
    volumes:
      - ./databases/main_db/bouncer-conf/etc/pgbouncer/:/etc/pgbouncer/:ro
      - ./workarea/sockets/main_db:/var/run/postgresql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: ${S_UID}:${S_GID}
    depends_on:
      - main_db
