services:
  web: 
    image:  nginx:1.29.4-alpine
    user: ${S_UID}:${S_GID}
    restart: ${RESTART_MODE}
    stop_signal: SIGTERM
    network_mode: ${NET_MODE}
#    ports:
#      - ${HOST_LOOPBACK_IP}:3080:80
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./src/app/common/servers/web/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/app/common/servers/web/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dist/web:/var/www/html:ro
      - ./workarea/sockets/web:/var/www/sockets
      - /etc/timezone:/etc/timezone:ro
    entrypoint: /etc/nginx/conf.d/nginx_start.sh
    init: true
    depends_on:
      - ext_app
