
user  nginx;
worker_processes  1; # TODO: it is dev setting!!! use auto in production 

error_log  /var/log/nginx/error.log notice;
#pid        /var/run/nginx.pid; # if root
pid        /tmp/nginx.pid;      # if containerized 

# this module builded by default in debian nginx-full
load_module modules/ngx_http_js_module.so; 

# this module builded by default in debian nginx-full
# but not installed in the official docker image 
# load_module modules/ngx_http_auth_request_module.so; 

events {
###S_DEL_PROD
    worker_connections  100;
###E_DEL_PROD

###E_UNCOMM_    worker_connections  40000;
}


http {

    # for unprivileged run (container dev mode)
    # in production, use default
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;


    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    resolver 127.0.0.11;

    js_engine qjs;

    include /etc/nginx/conf.d/*.conf;
}

stream {
    include /etc/nginx/conf.d/*.sconf;
}